## The following three one-dimensional arrays are given:

### feature1 = np.array([1.6, 0.9, 2.2])

### feature2 = np.array([0.4, 1.3, 3.2])

### feature3 = np.array([1.4, 0.3, 1.2])

## Transform each of these arrays into a column and concatenate them into one large array. Print result to the console.

## Tip: Use the function np.column_stack().

## Expected result:

#### [[1.6 0.4 1.4]

####  [0.9 1.3 0.3]

####  [2.2 3.2 1.2]]



In [1]:
import numpy as np

fea1 = np.array([1.6, 0.9, 2.2])
fea2 = np.array([0.4, 1.3, 3.2])
fea3 = np.array([1.4, 0.3, 1.2])

print(np.column_stack((fea1, fea2, fea3)))

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]


### The following two arrays A and B are given:

### A = np.array([[3, 4, 9, 2],              

### [5, 3, 2, 5]])

### B = np.array([[4, 3, 2, 5],              

### [6, 3, 1, 6]])

### Multiply arrays element-by-element (element-wise). Print result to the console.

### xpected result:

### [[12 12 18 10] 

### [30  9  2 30]]



In [2]:
import numpy as np

a = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
b = np.array([[4, 3, 2, 5], [6, 3, 1, 6]])

print(a*b)

[[12 12 18 10]
 [30  9  2 30]]


## Two arrays A and B are given below:

### A = np.array([[3, 4, 5],              

### [8, 3, 1]])

### B = np.array([[0, 5, 2],              

### [4, 2, 1]])

## Concatenate these arrays as follows:

### array([[3, 4, 5],       

### [8, 3, 1],       

### [0, 5, 2],       

### [4, 2, 1]])

###  Print result to the console.

## Tip: Use the np.concatenate() function.

## Expected result:

### [[3 4 5] 

### [8 3 1] 

### [0 5 2] 

### [4 2 1]]

In [3]:
import numpy as np

a = np.array([[3, 4, 5], [8, 3, 1]])
b = np.array([[0, 5, 2], [4, 2, 1]])

print(np.concatenate((a, b)))

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


## The following numpy array A is given:

### A = np.array([[3, 4, 9, 2],              

### [5, 3, 2, 5]])

### Determine the root of each element of the array A. Print result to the console.

### Tip: Use the np.sqrt() function.

### Expected result:

#### [[1.73205081 2.         3.         1.41421356] 

#### [2.23606798 1.73205081 1.41421356 2.23606798]]

In [4]:
import numpy as np

a = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])

print(np.sqrt(a))

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]


## The first array is given containing the data (data) and the second array containing the target class (target) for the given row:

### data = np.array([[4.3, 4.2],                 

### [3.1, 3.6]])

### target = np.array([[0],                   

### [1]])

### Concatenate these arrays into one as shown below:

### array([[4.3, 4.2, 0. ],       

### [3.1, 3.6, 1. ]])

### Print result to the console.

### Expected result:

#### [[4.3 4.2 0. ] 

#### [3.1 3.6 1. ]]



In [1]:
import numpy as np

a = np.array([[4.3, 4.2], [3.1, 3.6]])
b = np.array([[0], [1]])

print(np.concatenate((a, b), axis=1))

[[4.3 4.2 0. ]
 [3.1 3.6 1. ]]
