## Build the two-dimensional 6x6 size array below:

### [[0 0 0 0 0 0]

###  [0 1 0 0 0 0]

### [0 0 2 0 0 0]

### [0 0 0 3 0 0]

###  [0 0 0 0 4 0]

###  [0 0 0 0 0 5]]

### Tip: Use the np.diag() function.



In [1]:
import numpy as np
a = np.diag([i for i in range(6)])
print(a)

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


## Build a 6x6 two-dimensional array - identity matrix. Use the int data type. Print result to the console.

## Tip: Use the np.eye() function.

## Expected result:

### [[1 0 0 0 0 0]

###  [0 1 0 0 0 0]

###  [0 0 1 0 0 0]

###  [0 0 0 1 0 0]

###  [0 0 0 0 1 0]

###  [0 0 0 0 0 1]]



In [2]:
import numpy as np
print(np.eye(6, dtype='int32'))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


## Set the random seed to 20. Then build a two-dimensional array with the shape (10, 4) pseudo-random values generated from the standard normal distribution N(0,1).

## Tip: Use the function np.random.randn().

## Expected result:

#### [[ 0.88389311  0.19586502  0.35753652 -2.34326191]

####  [-1.08483259  0.55969629  0.93946935 -0.97848104]

####  [ 0.50309684  0.40641447  0.32346101 -0.49341088]

#### [-0.79201679 -0.84236793 -1.27950266  0.24571517]

####  [-0.0441948   1.56763255  1.05110868  0.40636843]

####  [-0.1686461  -3.18970279  1.12013226  1.33277821]

#### [-0.24333877 -0.13003071 -0.10901737  1.55618644]

####  [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]

####  [ 0.93286635  2.059838   -0.93493796 -1.61299022]

####  [ 0.52706972 -1.55110074  0.32961334 -1.13652654]]



In [3]:
import numpy as np
np.random.seed(20)
print(np.random.randn(10, 4))

[[ 0.88389311  0.19586502  0.35753652 -2.34326191]
 [-1.08483259  0.55969629  0.93946935 -0.97848104]
 [ 0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517]
 [-0.0441948   1.56763255  1.05110868  0.40636843]
 [-0.1686461  -3.18970279  1.12013226  1.33277821]
 [-0.24333877 -0.13003071 -0.10901737  1.55618644]
 [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]
 [ 0.93286635  2.059838   -0.93493796 -1.61299022]
 [ 0.52706972 -1.55110074  0.32961334 -1.13652654]]


## Create an array of numpy dimensions 10x10 filled with number 255. Set the data type to float.

## Tip: Use the np.ones() or np.full() functions.

## Expected result:

#### [[ 255.  255.  255.  255.  255.  255.  255.  255.  255.  255.]

#### [ 255.  255.  255.  255.  255.  255.  255.  255.  255.  255.]

#### [ 255.  255.  255.  255.  255.  255.  255.  255.  255.  255.]

#### [ 255.  255.  255.  255.  255.  255.  255.  255.  255.  255.]

#### [ 255.  255.  255.  255.  255.  255.  255.  255.  255.  255.]

#### [ 255.  255.  255.  255.  255.  255.  255.  255.  255.  255.]

#### [ 255.  255.  255.  255.  255.  255.  255.  255.  255.  255.]

#### [ 255.  255.  255.  255.  255.  255.  255.  255.  255.  255.]

#### [ 255.  255.  255.  255.  255.  255.  255.  255.  255.  255.]

#### [ 255.  255.  255.  255.  255.  255.  255.  255.  255.  255.]]

In [4]:
import numpy as np
a = np.zeros((10, 10))
a[:,:] = 255
print(a)


[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


## Build a one-dimensional numpy array of two-digit numbers. Print result to the console.

##  Tip: Use the np.arange() function.

## Expected result:


#### [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
####  35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59
####  60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84
####  85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]

In [5]:
import numpy as np
print(np.arange(10, 100))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


## Create an array of numpy dimensions 4x4 filled with zeros. Set the data type to int. Print result to the console.

## Tip: Use the np.zeros() function.

## Expected result:

#### [[0 0 0 0]

####  [0 0 0 0]

####  [0 0 0 0]

####  [0 0 0 0]]



In [6]:
import numpy as np
print(np.zeros((4, 4), dtype='int32'))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


##  Set the random seed to 10. Then build a one-dimensional array consisting of 30 pseudo-randomly generated values from the uniform distribution [0,1) interval. Print result to the console.

## Tip: Use the function np.random.rand().

## Expected result:

#### [ 0.77132064  0.02075195  0.63364823  0.74880388  0.49850701  0.22479665

####  0.19806286  0.76053071  0.16911084  0.08833981  0.68535982  0.95339335

####  0.00394827  0.51219226  0.81262096  0.61252607  0.72175532  0.29187607

####  0.91777412  0.71457578  0.54254437  0.14217005  0.37334076  0.67413362

####  0.44183317  0.43401399  0.61776698  0.51313824  0.65039718  0.60103895]

In [7]:
import numpy as np
np.random.seed(10)
print(np.random.rand(30))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895]


## Build the numpy array specified below:

#### [[10 11 12 13 14 15 16 17 18 19]

#### [20 21 22 23 24 25 26 27 28 29]

#### [30 31 32 33 34 35 36 37 38 39]

#### [40 41 42 43 44 45 46 47 48 49]

####  [50 51 52 53 54 55 56 57 58 59]

####  [60 61 62 63 64 65 66 67 68 69]

####  [70 71 72 73 74 75 76 77 78 79]

#### [80 81 82 83 84 85 86 87 88 89]

####  [90 91 92 93 94 95 96 97 98 99]]

## Note that the shape of the array is (9, 10). Print result to the console.

### Tip: Use the np.arange() function and the np.ndarray.reshape() method.

In [8]:
import numpy as np

a = np.arange(10, 100)
print(np.reshape(a, (9, 10)))


[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
